"""Schema-version constants for client-facing JSON artifacts."""

RUN_STATUS_SCHEMA_VERSION = "1"
PERFORMANCE_SCHEMA_VERSION = "1"
BENCHMARK_METRICS_SCHEMA_VERSION = "1"
COMPARISON_SUMMARY_SCHEMA_VERSION = "1"
