"""Schema contract for causal entry-state features."""
from __future__ import annotations

STATE_FIELDS: list[str] = [
    "ts",
    "symbol",
    "dataset_id",
    "signal_timeframe",
    "execution_timeframe",
    "entry_state_ema_fast",
    "entry_state_ema_slow",
    "entry_state_ema_relationship",
    "entry_state_ema_separation",
    "entry_state_ema_slope_fast",
    "entry_state_ema_slope_slow",
    "entry_state_trend_state",
    "entry_state_atr",
    "entry_state_atr_pct",
    "entry_state_atr_pct_pctile",
    "entry_state_vol_pctile",
    "entry_state_vol_regime",
    "entry_state_spread_proxy",
    "entry_state_spread_proxy_pctile",
    "entry_state_volume",
    "entry_state_dollar_volume",
    "entry_state_volume_z",
    "entry_state_volume_pctile",
    "entry_state_liquidity_regime",
    "entry_state_true_range",
    "entry_state_tr_over_atr",
    "entry_state_tr_over_atr_pctile",
    "entry_state_displacement_regime",
    "entry_state_csi_raw",
    "entry_state_csi_pctile",
    "entry_state_csi_bucket",
    "entry_state_time_of_day_bucket",
    "entry_state_day_of_week",
    "entry_state_asset_bucket",
    "entry_state_dataset_bucket",
    "entry_state_trend_ready",
    "entry_state_vol_ready",
    "entry_state_liquidity_ready",
    "entry_state_csi_ready",
    "entry_state_htf_ready",
]

PREFIX_GROUPS: dict[str, tuple[str, ...]] = {
    "identity": ("identity_",),
    "entry_state": ("entry_state_",),
    "entry_gate": ("entry_gate_",),
    "entry_decision": ("entry_decision_",),
    "execution": ("execution_",),
    "risk": ("risk_",),
    "path": ("path_",),
    "exit": ("exit_", "exit_reason"),
    "counterfactual": ("counterfactual_",),
    "label": ("label_",),
}
